### ISSUE TITLE
Broker is showing an Agent's contact information

### ISSUE THREAD

**Issue by hutch77** [DennisRSI/AdminBrokerClientAgentPortal#159] opened 2018-07-11 15:15 UTC
Dennis, I believe this is a holdover issue from old data when they didn't have Agents. Jenny explained that the Broker was changed from Scott Brunnenmeyer to Candy Bednar. It shows properly in the Broker list, but when you click through to her, it shows Scott's information as the contact and doesn't list Scott as an agent.

**Comment by patricksheedy** [comment] 2018-07-11 21:39
The problem is that the AspNetUsers data has incorrect information in it. I'm not sure how this happened, @DennisRSI probably has a better idea of what is going on here.

Example of the problem:
USE [AdminBrokerClientPortal1]
GO

SELECT *
  FROM [dbo].[AspNetUsers]
  where Id = '20bfe064-952f-496e-a829-ea92c01f7f80'
GO

**Comment by patricksheedy** [comment] 2018-07-12 21:52
I need to do further testing on this to see if the problem can be reproduced.

**Comment by patricksheedy** [comment] 2018-07-13 17:23
I wasn't able to reproduce this on QA, if I made an edit the data was also changed in the identity database. I'm not sure how the data got into this state.

**Comment by patricksheedy** [comment] 2018-07-13 19:44
A bug is fixed in the latest code that allows the broker to be updated. After the new build is deployed, Jenny will need to edit the Broker and update to the correct information.

**Comment by hutch77** [comment] 2018-07-17 19:05
I'll reach out to Jenny and find out what still needs to be edited. It all looks like it's Candy' information except the email address is still for Scott Brunnenmeyer. I can't change that - see issue #169 - this would have to be changed in the database, not by a logged in user.

**Comment by patricksheedy** [comment] 2018-07-17 23:25
You can edit the broker's email address now on production.

**Closed as completed** 2018-10-12 17:10 UTC
Labels: invalid
